version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps):"
    allow:
      - dependency-name: "@redhat-cloud-services/frontend*"
      - dependency-name: "@patternfly/*"
        dependency-type: direct
    ignore:
      - dependency-name: "react-router-dom"
        versions: ["6.x"]
    groups:
      redhat-cloud-services:
        patterns:
          - "@redhat-cloud-services/*"
        exclude-patterns:
          - "@redhat-cloud-services/*-client"
      patternfly:
        patterns:
          - "@patternfly/*"
        exclude-patterns:
          - "@patternfly/react-charts"
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      rollup:
        patterns:
          - "rollup"
          - "@rollup/plugin*"
          - "rollup-plugin*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
