language: node_js
sudo: required
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
after_success:
- npm run travis-deploy-once "npm run semantic-release"
- curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
  global:
  - REPO="git@github.com:RedHatInsights/vulnerability-ui-build"
  - REPO_DIR="vulnerability-ui-build"
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
