language: node_js
sudo: required
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
after_success:
- ".travis/after_success"
env:
  global:
  - REPO="git@github.com:RedHatInsights/vulnerability-ui-build"
  - REPO_DIR="vulnerability-ui-build"
before_install:
- openssl aes-256-cbc -K $encrypted_d87ac36486e0_key -iv $encrypted_d87ac36486e0_iv
  -in deploy_key.enc -out deploy_key -d
