version: '3'
services:
  ui:
    build: .
    network_mode: "host"
    ports:
    - "8002:8002"
    volumes:
    - ./src/:/frontend/src:Z
    command: /usr/bin/npm run start
  proxy:
    image: redhatinsights/insights-proxy
    network_mode: "host"
    ports:
    - "1337:1337" 
    environment:
    - PLATFORM=linux
    - PORT=8002
    - LOCAL_API=false

